// /utils/tarotCardMapping.js
export const tarotCardMapping = {
  "The Fool": "00-TheFool.jpg",
  "The Magician": "01-TheMagician.jpg",
  "The High Priestess": "02-TheHighPriestess.jpg",
  "The Empress": "03-TheEmpress.jpg",
  "The Emperor": "04-TheEmperor.jpg",
  "The Hierophant": "05-TheHierophant.jpg",
  "The Lovers": "06-TheLovers.jpg",
  "The Chariot": "07-TheChariot.jpg",
  "Strength": "08-Strength.jpg",
  "The Hermit": "09-TheHermit.jpg",
  "Wheel of Fortune": "10-WheelOfFortune.jpg",
  "Justice": "11-Justice.jpg",
  "The Hanged Man": "12-TheHangedMan.jpg",
  "Death": "13-Death.jpg",
  "Temperance": "14-Temperance.jpg",
  "The Devil": "15-TheDevil.jpg",
  "The Tower": "16-TheTower.jpg",
  "The Star": "17-TheStar.jpg",
  "The Moon": "18-TheMoon.jpg",
  "The Sun": "19-TheSun.jpg",
  "Judgement": "20-Judgement.jpg",
  "The World": "21-TheWorld.jpg",
  // Wands
    'Ace of Wands': 'Wands01.jpg',
    'Two of Wands': 'Wands02.jpg',
    'Three of Wands': 'Wands03.jpg',
    'Four of Wands': 'Wands04.jpg',
    'Five of Wands': 'Wands05.jpg',
    'Six of Wands': 'Wands06.jpg',
    'Seven of Wands': 'Wands07.jpg',
    'Eight of Wands': 'Wands08.jpg',
    'Nine of Wands': 'Wands09.jpg',
    'Ten of Wands': 'Wands10.jpg',
    'Page of Wands': 'Wands11.jpg',
    'Knight of Wands': 'Wands12.jpg',
    'Queen of Wands': 'Wands13.jpg',
    'King of Wands': 'Wands14.jpg',
    // Cups
    'Ace of Cups': 'Cups01.jpg',
    'Two of Cups': 'Cups02.jpg',
    'Three of Cups': 'Cups03.jpg',
    'Four of Cups': 'Cups04.jpg',
    'Five of Cups': 'Cups05.jpg',
    'Six of Cups': 'Cups06.jpg',
    'Seven of Cups': 'Cups07.jpg',
    'Eight of Cups': 'Cups08.jpg',
    'Nine of Cups': 'Cups09.jpg',
    'Ten of Cups': 'Cups10.jpg',
    'Page of Cups': 'Cups11.jpg',
    'Knight of Cups': 'Cups12.jpg',
    'Queen of Cups': 'Cups13.jpg',
    'King of Cups': 'Cups14.jpg',
    // Swords
    'Ace of Swords': 'Swords01.jpg',
    'Two of Swords': 'Swords02.jpg',
    'Three of Swords': 'Swords03.jpg',
    'Four of Swords': 'Swords04.jpg',
    'Five of Swords': 'Swords05.jpg',
    'Six of Swords': 'Swords06.jpg',
    'Seven of Swords': 'Swords07.jpg',
    'Eight of Swords': 'Swords08.jpg',
    'Nine of Swords': 'Swords09.jpg',
    'Ten of Swords': 'Swords10.jpg',
    'Page of Swords': 'Swords11.jpg',
    'Knight of Swords': 'Swords12.jpg',
    'Queen of Swords': 'Swords13.jpg',
    'King of Swords': 'Swords14.jpg',
    // Pentacles
    'Ace of Pentacles': 'Pentacles01.jpg',
    'Two of Pentacles': 'Pentacles02.jpg',
    'Three of Pentacles': 'Pentacles03.jpg',
    'Four of Pentacles': 'Pentacles04.jpg',
    'Five of Pentacles': 'Pentacles05.jpg',
    'Six of Pentacles': 'Pentacles06.jpg',
    'Seven of Pentacles': 'Pentacles07.jpg',
    'Eight of Pentacles': 'Pentacles08.jpg',
    'Nine of Pentacles': 'Pentacles09.jpg',
    'Ten of Pentacles': 'Pentacles10.jpg',
    'Page of Pentacles': 'Pentacles11.jpg',
    'Knight of Pentacles': 'Pentacles12.jpg',
    'Queen of Pentacles': 'Pentacles13.jpg',
    'King of Pentacles': 'Pentacles14.jpg',
  };

export function getCardFileName(cardName) {
  return tarotCardMapping[cardName] || '00-TheFool.jpg'; // Default về The Fool nếu không tìm thấy
}